### ISSUE TITLE
macOS Big Sur, any possibility ?

### ISSUE THREAD

**Issue by VladAlexandru2000** [Tonymiugrey/Garden-by-miugrey#24] opened 2020-07-10 20:08 UTC

**Comment by Tonymiugrey** [comment] 2020-07-10 22:04
Just wait for it 😊 I'm testing OC these days.

**Comment by VladAlexandru2000** [comment] 2020-07-10 23:55
I installed Big Sur Beta 2 and work very good but some things not working perfect !

**Comment by VladAlexandru2000** [comment] 2020-07-10 23:55
I used Clover !

**Comment by Tonymiugrey** [comment] 2020-07-11 07:07
Wow great! Which version of Clover and how about the bugs you met?
I think OC will be better for the future versions of macOS so I decide to make a transition to it.

**Comment by VladAlexandru2000** [comment] 2020-07-11 08:41
I used modified version of clover from a german site for hackintosh.

**Comment by VladAlexandru2000** [comment] 2020-07-11 08:43
Sata drive not working, bettery not showing in setting, touchpad works but not appering in settings.

**Comment by arepson** [comment] 2020-07-11 10:30
> I think OC will be better for the future versions of macOS so I decide to make a transition to it.

And OC more faster than Clover, Good luck Tony

**Comment by Tonymiugrey** [comment] 2020-07-13 09:47
> Sata drive not working, battery not showing in setting, touchpad works but not appering in settings.
Did you try the same EFI on Catalina?

I think I will try Big Sur after it is stable enough.

**Comment by VladAlexandru2000** [comment] 2020-07-13 09:49
yes, same EFI, but I have some problems.

**Comment by Tonymiugrey** [comment] 2020-07-13 12:54
Could you sent me your efi?

**Comment by VladAlexandru2000** [comment] 2020-07-13 23:02
Yes, but you need to put your `config.plist` and open it and copy at the KernelAndKextPatches 3 lines from the 
`config_KernelAndKextPatches.plist`
[EFI Big Sur.zip](https://github.com/Tonymiugrey/Garden-by-miugrey/files/4915565/EFI.Big.Sur.zip)

**Comment by VladAlexandru2000** [comment] 2020-07-13 23:06
After that you are not able to boot big sur installer, need to restore a preinstalled image !

**Comment by VladAlexandru2000** [comment] 2020-07-13 23:17
I have a preinstalled image, but i don't know to share it to you !

**Comment by Tonymiugrey** [comment] 2020-07-13 23:36
Temporary I want to wait for the stable version of Big Sur. I will test it on the Catalina and try to fix bugs. Thanks!

**Comment by arepson** [comment] 2020-07-14 02:02
> Temporary I want to wait for the stable version of Big Sur. I will test it on the Catalina and try to fix bugs. Thanks!

I'm so excited to wait your OC

**Comment by arepson** [comment] 2020-07-17 00:22
Can you give us an estimate when you will release the OC version?

**Comment by Tonymiugrey** [comment] 2020-07-17 00:25
> Can you give us an estimate when you will release the OC version?

It's hard to say because I'm a student, still need to prepare for two exams and a competition... So I can only do this in my spare time

**Comment by arepson** [comment] 2020-07-28 05:42
Any update about OC?

**Comment by Tonymiugrey** [comment] 2020-07-28 05:52
Sorry that I'm busy these days and have no time to fix the bugs...

Maybe I'll release them in the end of August, or the beginning of September.

**Comment by arepson** [comment] 2020-07-28 06:24
Okay thanks👌 Good luck

**Comment by arepson** [comment] 2020-08-12 11:53
Any update about OC?

**Comment by Tonymiugrey** [comment] 2020-08-12 11:58
Bugs of CPU frequency has fixed. Still need some time.

**Comment by VladAlexandru2000** [comment] 2020-08-12 23:49
what fix do you use for opencore webcam

**Comment by Tonymiugrey** [comment] 2020-08-13 02:40
> what fix do you use for webcam on opencore ?

patch the usb ports.

**Comment by Tonymiugrey** [comment] 2020-08-13 16:15
I find a guy who have already made an OC based on my clover. But there're still some problems. We are manage to make it better these days. See you guys soon!

**Comment by Tonymiugrey** [comment] 2020-08-13 16:16
His OC works better than mine.

**Comment by VladAlexandru2000** [comment] 2020-08-13 20:32
you are great man, I'm waiting for you to launch your stable version of oc !

**Comment by arepson** [comment] 2020-08-13 22:53
will it be released in a few days?

**Comment by VladAlexandru2000** [comment] 2020-08-16 08:29
what exactly needs to be changed if I don't have PM981 at at OC 4.0 Beta ?

**Comment by Tonymiugrey** [comment] 2020-08-16 10:00
> what exactly needs to be changed if I don't have PM981 at at OC 4.0 Beta ?

Deselect SSDT-NVME.aml and Hacknvme… .kext in config.plist through OC configurator

**Comment by VladAlexandru2000** [comment] 2020-08-16 13:41
Thanks man , you are great !

**Comment by arepson** [comment] 2020-08-23 23:27
Any update?

**Comment by VladAlexandru2000** [comment] 2020-08-25 08:21
fix for cpu frequency ?

**Comment by Tonymiugrey** [comment] 2020-08-25 08:23
> fix for cpu frequency ?

Still finding what cause that problem

**Comment by VladAlexandru2000** [comment] 2020-08-25 08:27
Is super annoying bug !

**Comment by arepson** [comment] 2020-09-07 06:17
Any update about fix for CPU frequency?

**Comment by VladAlexandru2000** [comment] 2020-09-28 11:32
Fix for cpu frequency ?

**Comment by Tonymiugrey** [comment] 2020-09-28 12:35
> Fix for cpu frequency ?

Fixed. Will release it in a few days. Still a beta version.

**Comment by VladAlexandru2000** [comment] 2020-09-28 12:36
Ok, man !

**Comment by arepson** [comment] 2020-10-04 23:29
When update release?

**Comment by VladAlexandru2000** [comment] 2020-10-06 22:36
when you release update ?

**Comment by arepson** [comment] 2020-10-14 02:33
When update release?

**Comment by VladAlexandru2000** [comment] 2020-10-24 09:42
what does a few days mean?

**Comment by Tonymiugrey** [comment] 2020-10-25 03:37
I’m so sorry for a long time waiting TAT
I decided to test the beta versions in a Chinese chatting group for better communication.
Once it becomes stable enough, I will put it here. Maybe it will around the time that Apple releases the stable version of Big Sur... I’m not sure because I’m busy these days, but the friends in that group helped me to fix a lot of bugs. I believe we will finish this work soon...
And the Clover version for Big Sur will be released in the same day.  I will continually update the Clover version until the OC version brings the best macOS experience to this laptop. You know, these two bootloaders are woking differently...
Sorry again!

**Comment by arepson** [comment] 2020-10-25 11:30
At least tell us about the progress on the projects menu

**Comment by Tonymiugrey** [comment] 2020-10-25 11:35
I seldom come to here because my energy is limited :( I will notice that next time

**Comment by Tonymiugrey** [comment] 2020-11-02 17:40
Things going far beyond our expectations :)

**Comment by VladAlexandru2000** [comment] 2020-11-02 22:21
> Things going far beyond our expectations :)


What exactly do you mean?

**Comment by arepson** [comment] 2020-11-02 22:23
Make the Hackintosh user experience on the HP Pavilion Gaming 15 like the real MacBook

**Comment by VladAlexandru2000** [comment] 2020-11-02 22:26
> Make the Hackintosh user experience on the HP Pavilion Gaming 15 like the real MacBook

That sounds great !

**Comment by Tonymiugrey** [comment] 2020-11-03 00:24
> Make the Hackintosh user experience on the HP Pavilion Gaming 15 like the real MacBook

Yes, including FileVault2, switching Windows and macOS directly in the system (macOS: Preference>Startup Disk, Windows: install Boot Camp Utility) and Intelwifi (Universal clipboard and handoff is available, airdrop will coming soon)

**Comment by VladAlexandru2000** [comment] 2020-11-03 06:07
About what date do you estimate that you will launch it or at least in what month?

**Comment by Tonymiugrey** [comment] 2020-11-03 06:15
> I’m so sorry for a long time waiting TAT
> I decided to test the beta versions in a Chinese chatting group for better communication.
> Once it becomes stable enough, I will put it here. Maybe it will around the time that Apple releases the stable version of Big Sur... I’m not sure because I’m busy these days, but the friends in that group helped me to fix a lot of bugs. I believe we will finish this work soon...
> And the Clover version for Big Sur will be released in the same day. I will continually update the Clover version until the OC version brings the best macOS experience to this laptop. You know, these two bootloaders are woking differently...
> Sorry again!

Said.

**Comment by VladAlexandru2000** [comment] 2020-11-03 06:17
OK, Thanks !

**Comment by Tonymiugrey** [comment] 2020-11-03 06:17
Clover version of that laptop may not receive update anymore.

**Comment by RaffaySajjad** [comment] 2020-11-03 06:29
For anyone waiting for Tonymiugrey's EFI. You are free to test my EFI. It is based on OC 0.6.2 and tested on several latest builds. Try https://github.com/RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI-

**Comment by arepson** [comment] 2020-11-03 06:33
> For anyone waiting for Tonymiugrey's EFI. You are free to test my EFI. It is based on OC 0.6.2 and tested on several latest builds (Including Big Sur). Try https://github.com/RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI-

It's support dual boot with Windows?

**Comment by Tonymiugrey** [comment] 2020-11-03 06:34
> For anyone waiting for Tonymiugrey's EFI. You are free to test my EFI. It is based on OC 0.6.2 and tested on several latest builds (Including Big Sur). Try https://github.com/RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI-

COOL bro! How about sleep 'n wake, battery life and the stability of PM981?

**Comment by RaffaySajjad** [comment] 2020-11-03 06:34
> > For anyone waiting for Tonymiugrey's EFI. You are free to test my EFI. It is based on OC 0.6.2 and tested on several latest builds (Including Big Sur). Try https://github.com/RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI-
> 
> It's support dual boot with Windows?

Yes. It supports dual booting.

**Comment by RaffaySajjad** [comment] 2020-11-03 06:35
> > For anyone waiting for Tonymiugrey's EFI. You are free to test my EFI. It is based on OC 0.6.2 and tested on several latest builds (Including Big Sur). Try https://github.com/RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI-
> 
> COOL bro! How about sleep 'n wake, battery life and the stability of PM981?

Thanks bro. Sleep is working perfectly for me. As for the SSD, my laptop doesn't have a PM981 SSD. Its equipped with a Toshiba one. So I didn't face any issue at that front :)

**Comment by Tonymiugrey** [comment] 2020-11-03 06:37
Ok I think that problem is probably caused by Pm981 with error report of nvme

**Comment by RaffaySajjad** [comment] 2020-11-03 06:38
Probably. PM981 is known to cause trouble on mackintoshes. Especially Sleep/Wake issues.

**Comment by VladAlexandru2000** [comment] 2020-11-03 06:46
I took out PM981 and put a 970 EVO, PM981 had too little capacity!

**Comment by arepson** [comment] 2020-11-03 06:49
My PM981 still inside but I'm replace the HDD with Samsung 860 Evo.

**Comment by Tonymiugrey** [comment] 2020-11-03 06:50
> I took out PM981 and put a 970 EVO, PM981 had too little capacity!

I will replace it too if I were not a student :( It's too fking unstable.

**Comment by VladAlexandru2000** [comment] 2020-11-03 15:00
> For anyone waiting for Tonymiugrey's EFI. You are free to test my EFI. It is based on OC 0.6.2 and tested on several latest builds (Including Big Sur). Try https://github.com/RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI-

On my laptop, this opencore version working perfect ! Thank Youu !

**Comment by arepson** [comment] 2020-11-03 15:02
> On my laptop, this opencore version working perfect ! Thank Youu !

How about dual boot? Windows EFI not show in Grub OpenCore

**Comment by RaffaySajjad** [comment] 2020-11-03 15:39
> > For anyone waiting for Tonymiugrey's EFI. You are free to test my EFI. It is based on OC 0.6.2 and tested on several latest builds (Including Big Sur). Try https://github.com/RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI-
> 
> On my laptop, this opencore version working perfect ! Thank Youu !

Glad I could help :)

**Comment by VladAlexandru2000** [comment] 2020-11-03 19:26
> > On my laptop, this opencore version working perfect ! Thank Youu !
> 
> How about dual boot? Windows EFI not show in Grub OpenCore

I am using separate drive for windows and separte drive for macOS !

**Comment by arepson** [comment] 2020-11-11 17:26
@Tonymiugrey any progress?

**Comment by VladAlexandru2000** [comment] 2020-11-13 11:32
Any progress, the official version of Big Sur (20B29) has been released !

**Comment by Tonymiugrey** [comment] 2020-11-13 11:36
I think it will work well on 20B29 (sleep and wake still buggy on Pm981) and will release it tomorrow night

**Comment by arepson** [comment] 2020-11-13 11:38
Can you help me? I'm use OC from @RaffaySajjad but directly boot to Windows, not OpenCore Grub. In Bios not detect OpenCore'(

**Comment by VladAlexandru2000** [comment] 2020-11-13 11:40
> I think it will work well on 20B29 (sleep and wake still buggy on Pm981) and will release it tomorrow night

I no longer have PM981, so for me everything will work perfectly, I guess you will launch a separate version for those who do not have PM981!

**Comment by arepson** [comment] 2020-11-13 11:43
> I think it will work well on 20B29 (sleep and wake still buggy on Pm981) and will release it tomorrow night

Oh yeah, I'm forget. When I'm used OC From @RaffaySajjad with my SSD PM981, I'm try mount EFI (Because I'm place the OC in EFI PM981) immediately get KP'(

**Comment by Tonymiugrey** [comment] 2020-11-13 11:44
Everything works well on Catalina except sleep n wake

**Comment by Tonymiugrey** [comment] 2020-11-13 11:46
> Can you help me? I'm use OC from @RaffaySajjad but directly boot to Windows, not OpenCore Grub. In Bios not detect OpenCore'(

Try EasyUEFI on Windows to create an item for OC and set it to the default boot item(move it to the top)

**Comment by VladAlexandru2000** [comment] 2020-11-13 11:46
> Can you help me? I'm use OC from @RaffaySajjad but directly boot to Windows, not OpenCore Grub. In Bios not detect OpenCore'(

I also use @RaffaySajjad's OpenCore and if I want to boot on Windows it gives me BSOD! I boot macOS directly from the BootMenu on F9 and Windows starts normally! It would be interesting if I could switch between OS directly (From macOS to Windows and vice versa).

**Comment by Tonymiugrey** [comment] 2020-11-13 11:48
> > Make the Hackintosh user experience on the HP Pavilion Gaming 15 like the real MacBook
> 
> Yes, including FileVault2, switching Windows and macOS directly in the system (macOS: Preference>Startup Disk, Windows: install Boot Camp Utility) and Intelwifi (Universal clipboard and handoff is available, airdrop will coming soon)

Mentioned

**Comment by VladAlexandru2000** [comment] 2020-11-13 11:53
I have windows on separate drive !
Windows on NVME 970 EVO
MacOS on SATA 860 EVO

**Comment by Tonymiugrey** [comment] 2020-11-13 11:54
I guess it doesn't matter

**Comment by VladAlexandru2000** [comment] 2020-11-13 11:56
Where can I find the BOOTCAMP Utility for windows 10?

**Comment by arepson** [comment] 2020-11-13 11:56
> I have windows on separate drive !
> Windows on NVME 970 EVO
> MacOS on SATA 860 EVO

Where you place your EFI? in same drive?

**Comment by Tonymiugrey** [comment] 2020-11-13 11:58
> Where can I find the BOOTCAMP Utility for windows 10?

boot camp app in macOS. One of the menus in the top bar provide that item

**Comment by VladAlexandru2000** [comment] 2020-11-13 12:00
> > I have windows on separate drive !
> > Windows on NVME 970 EVO
> > MacOS on SATA 860 EVO
> 
> Where you place your EFI? in same drive?

Each drive with EFI partition
OpenCore EFI on 860 EVO
Microsoft EFI  on 970 EVO

**Comment by Tonymiugrey** [comment] 2020-11-13 12:01
> > I have windows on separate drive !
> > Windows on NVME 970 EVO
> > MacOS on SATA 860 EVO
> 
> Where you place your EFI? in same drive?

I haven't tested it yet, but OC may detect all of the OS you installed in your computer automaticly, I guess.

**Comment by VladAlexandru2000** [comment] 2020-11-13 12:03
It detects it but if I want to boot it, BSOD results!

**Comment by Tonymiugrey** [comment] 2020-11-13 12:04
> It detects it but if I want to boot it, BSOD results!

Wrong SSDT cause that.

**Comment by VladAlexandru2000** [comment] 2020-11-13 12:05
![Uploading AF5D66B4-303B-4E89-A7C8-659B88E7D81F.jpeg…]()

**Comment by VladAlexandru2000** [comment] 2020-11-13 12:06
![Uploading 642B08F3-9B92-4FDF-B17F-57E0BD53A368.jpeg…]()

**Comment by VladAlexandru2000** [comment] 2020-11-13 12:11
![IMG_5196](https://user-images.githubusercontent.com/66947407/99071016-0603f700-25ba-11eb-966e-d8a365b5976b.jpg)

**Comment by Tonymiugrey** [comment] 2020-11-13 12:12
> > It detects it but if I want to boot it, BSOD results!
> 
> Wrong SSDT cause that.

。

**Comment by VladAlexandru2000** [comment] 2020-11-13 12:13
> > > It detects it but if I want to boot it, BSOD results!
> > 
> > 
> > Wrong SSDT cause that.
> 
> 。

Which of the SSDTs creates the problem?

**Comment by Tonymiugrey** [comment] 2020-11-13 12:15
Many...In the version I released in summer.

**Comment by VladAlexandru2000** [comment] 2020-11-13 12:19
Okay, I'll wait until tomorrow when you launch your version of opencore, I guess you managed to boot on windows from opencore.

**Comment by VladAlexandru2000** [comment] 2020-11-13 13:24
BootCamp Utility install error on windows(not compatible)

**Comment by Tonymiugrey** [comment] 2020-11-13 13:26
You should boot Windows through oc, which makes the installer think that it runs on a real mac

**Comment by VladAlexandru2000** [comment] 2020-11-13 13:29
boot from oc windows get BSOD :(

**Comment by VladAlexandru2000** [comment] 2020-11-13 13:30
on your oc boot windows without BSOD ?

**Comment by Tonymiugrey** [comment] 2020-11-13 13:30
> on your oc boot windows without BSOD ?

I have said that.

**Comment by Tonymiugrey** [comment] 2020-11-13 13:32
just wait.

**Comment by VladAlexandru2000** [comment] 2020-11-13 13:34
I'm very curious, I can't wait, I'm impatient :)))

**Comment by Tonymiugrey** [comment] 2020-11-13 13:37
Keep patient bro😂

**Comment by arepson** [comment] 2020-11-14 06:07
I can't wait 😟

**Comment by VladAlexandru2000** [comment] 2020-11-14 15:13
What time do you expect to launch it?

**Closed** 2020-11-14 16:29 UTC
Labels: bug, enhancement
